name: flutter_beertastic
description: Beertastic application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.5
  firebase_auth:  ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  cloud_functions: ^0.5.0

  google_sign_in: ^4.0.2

  google_maps_flutter: ^0.5.29
  flutter_google_maps: ^4.0.0
  geolocator: ^5.3.2+2
  permission_handler: ^5.0.1+1
  image_picker: ^0.6.7+4
  flutter_rating_bar: ^3.0.1+1

  url_launcher: ^5.5.0

  provider: ^4.3.2

  #
  rect_getter: 0.1.0

  auto_size_text: ^2.1.0

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  #Design packages
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^1.0.2
  flare_flutter: ^2.0.6

  shared_preferences: ^0.5.8

  synchronized: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  gen_lang: 0.1.0
# The following section is specific to Flutter.
flutter:

  # include material design
  uses-material-design: true

  # assets
  assets:
    - assets/images/logo.png
    - assets/images/user.png
    - assets/images/3042.jpg
    - assets/images/milan.jpg
    - assets/animations/simple_color_bar.flr

  fonts:
    - family:  CustomIcons
      fonts:
        - asset: assets/icons/beer_icon.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: NotoSans-Bold
      fonts:
        - asset: assets/fonts/NotoSans-Bold.ttf
    - family: Moon-Light
      fonts:
        - asset: assets/fonts/Moon2.0-Light.otf
    - family: Moon
      fonts:
        - asset: assets/fonts/Moon2.0-Regular.otf
    - family: Moon-Bold
      fonts:
        - asset: assets/fonts/Moon2.0-Bold.otf
    - family: Berkshire Swash
      fonts:
        - asset: assets/fonts/Berkshire_Swash.ttf
    - family: PlayfairDisplay Bold
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
    - family: PlayfairDisplay Regular
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
    - family: Open Sans SemiBold
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
    - family: Open Sans Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Open Sans Bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
    - family: Montserrat Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Montserrat SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Montserrat Regular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: TimeBurner Regular
      fonts:
        - asset: assets/fonts/timeburnernormal.ttf
    - family: TimeBurner Bold
      fonts:
        - asset: assets/fonts/timeburnerbold.ttf
    - family: Audrey Bold
      fonts:
        - asset: assets/fonts/Audrey-Bold.otf
    - family: Canvas Bold
      fonts:
        - asset: assets/fonts/Canvas-Bold.otf
    - family: Nunito Black
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
    - family: Nunito Bold
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: Nunito Regular
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family:  Campton Bold
      fonts:
        - asset: assets/fonts/Campton-Bold.otf
    - family:  Campton Thin
      fonts:
        - asset: assets/fonts/Campton-Bold.otf