version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor -v
      - run:
          name: show app tree
          command: |
            find ./lib -type d -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'
      - run: flutter test
      - run:
          name: coverage
          command: |
            flutter test --coverage
            bash <(curl -s https://codecov.io/bash) -t ${codecov_token}
      - run:
          name: flutter build
          command: |
            flutter build apk --debug --split-per-abi
            flutter build apk --profile --split-per-abi
            flutter build apk --split-per-abi


