version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor -v
      - run:
          name: show app tree
          command: |
            find ./lib -type d -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'
      - run: flutter test 

